export const graphData = {
  id: 1,
  current_age: 25,
  title: 'My Life Graph',
  events: [
    {
      age: 10,
      score: 4,
      title: 'Started school',
      description: 'Started elementary school',
    },
  ],
  created_at: '2024-09-17T00:00:00.000Z',
  updated_at: '2024-09-17T00:00:00.000Z',
};

export const graphListData = {
  data: [
    {
      id: 1,
      current_age: 25,
      title: 'My Life Graph',
      events: [
        {
          age: 10,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 11,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 15,
          score: -1,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 17,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 19,
          score: -5,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 20,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 21,
          score: -4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 22,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 23,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 24,
          score: -1,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 25,
          score: -2,
          title: 'Started school',
          description: 'Started elementary school',
        },
      ],
      created_at: '2024-09-17T00:00:00.000Z',
      updated_at: '2024-09-17T00:00:00.000Z',
    },
    {
      id: 1,
      current_age: 25,
      title: 'My Life Graph',
      events: [
        {
          age: 10,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 11,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 14,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 17,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 19,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 20,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 21,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 22,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 23,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 24,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 25,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
      ],
      created_at: '2024-09-17T00:00:00.000Z',
      updated_at: '2024-09-17T00:00:00.000Z',
    },
    {
      id: 1,
      current_age: 25,
      title: 'My Life Graph',
      events: [
        {
          age: 10,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 11,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 14,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 17,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 19,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 20,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 21,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 22,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 23,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 24,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
        {
          age: 25,
          score: 4,
          title: 'Started school',
          description: 'Started elementary school',
        },
      ],
      created_at: '2024-09-17T00:00:00.000Z',
      updated_at: '2024-09-17T00:00:00.000Z',
    },
  ],
  totalCount: 10,
};
